POST http://localhost:3000/getToken
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}


###
GET http://localhost:3000/cards?set=Base
Content-Type: application/json
